### ISSUE TITLE
Should Markdown Front Matter be indented with 4 spaces?

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/cone-site#4]
Currently it uses mixed 2 and 4 space indents.
https://github.com/conedevelopment/cone-site/blob/f8433015e516b119e0ba6f926e3d01c16ae1ea51/src/works.md?plain=1#L19-L28

https://github.com/conedevelopment/cone-site/blob/f8433015e516b119e0ba6f926e3d01c16ae1ea51/.editorconfig#L8

It would be nice to see 4 space indentations everywhere, even in Sass files!

**Comment by adamlaki** [comment]
As I see this should be 4 but my IDE switches to 2 when there is a "-". I think because to keep the line on the oter elements.

It seems to me that this is a feature.

![image](https://github.com/conedevelopment/cone-site/assets/5145299/c6343f02-1c61-49f3-9820-217f14a4d78a)

**Comment by szepeviktor** [comment]
There is a solution in the [YAML Spec](https://yaml.org/spec/1.2.2/#21-collections) / "Example 2.4 Sequence of Mappings".
It will feel strange!! 😨

It goes like PSR-12 in PHP
```php
    public function i_want_to_be_separated_from_function_body()
    { 👈🏻 this almost empty line does the separation
        $this->do_it();
    }
```

Now let's see in YAML!
```yaml
important_values:
- 👈🏻 this almost empty line does the separation
    title: Symphonie Nr. 40 G minor
    composer: Madi Mozart
-
    title: next item
    composer: is also a PHP tool
```

See it [in action](https://github.com/szepeviktor/byte-level-care/blob/a9490b89da7f6840384077594f08d6076ee0039b/.github/workflows/front-end.yml#L46): separation but no blank lines.
